[package]
name = "gfimx"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5.4"
data-encoding = "2.3.2"
reflux = "0.1.2"
mbfs = "0.1.6"
sha2 = "0.10.2"
