[package]
name = "gfimx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.reflexive_queue]
path = "./lib/reflexive_queue"